# Generated by Django 2.2.1 on 2021-08-27 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=6)),
                ('product_id', models.CharField(max_length=6)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='追加日時')),
            ],
            options={
                'verbose_name': 'カートデータ',
                'verbose_name_plural': 'カートデータ',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('age', models.IntegerField(verbose_name='年齢')),
                ('gender', models.IntegerField(choices=[(0, '男性'), (1, '女性')], verbose_name='性別')),
                ('household_num', models.IntegerField(verbose_name='世帯人数')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'ユーザー情報データ',
                'verbose_name_plural': 'ユーザー情報データ',
            },
        ),
        migrations.CreateModel(
            name='RentRoom',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='物件ID')),
                ('pref_name', models.CharField(max_length=20, verbose_name='都道府県')),
                ('city_name', models.CharField(max_length=50, verbose_name='市区町村')),
                ('district_name', models.CharField(max_length=50, verbose_name='町丁目')),
                ('built_year', models.IntegerField(verbose_name='築年')),
                ('structure', models.CharField(max_length=20, verbose_name='構造')),
                ('top_floor_num', models.IntegerField(verbose_name='最上階数')),
                ('room_type', models.CharField(max_length=20, verbose_name='間取り')),
                ('price', models.FloatField(verbose_name='平米単価')),
                ('area', models.FloatField(verbose_name='専有面積')),
                ('latitude', models.FloatField(verbose_name='物件緯度')),
                ('longitude', models.FloatField(verbose_name='物件経度')),
                ('nearest_station', models.CharField(max_length=50, verbose_name='最寄り駅')),
                ('dist_to_nearest_station', models.FloatField(verbose_name='最寄駅までの距離')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iekari.Profile', verbose_name='所有者')),
            ],
            options={
                'verbose_name': '物件情報データ',
                'verbose_name_plural': '物件情報データ',
            },
        ),
        migrations.CreateModel(
            name='ScoreLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='評価')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='日時')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iekari.Profile', verbose_name='ユーザー情報')),
                ('rent_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iekari.RentRoom', verbose_name='物件')),
            ],
            options={
                'verbose_name': '賃貸物件評価データ',
                'verbose_name_plural': '賃貸物件評価データ',
            },
        ),
    ]
